Add contributor form into app
Couchers-org/couchers pull request #1027
Opened 2021-04-08 13:25 UTC by aapeliv

2021-04-11 17:01 UTC, aapeliv commented
@kalvdans: could you please review backend bit, it's tiny :)

2021-04-11 18:10 UTC, aapeliv commented
I've done an awful hack to get checkboxes and have them turned nicely into a comma-delimited string...

2021-04-11 18:12 UTC, kalvdans submitted a review, later dismissed
backend looks solid

2021-04-12 00:08 UTC, darrenvong requested changes
Hopefully I caught most things

2021-04-12 00:08 UTC, darrenvong commented on app/frontend/src/features/contributorForm/ContributorForm.tsx
> +        const info = await service.account.getContributorFormInfo();
It's probably easier and safer to do this with React Query, since it's easy for this kinda async stuff to run into the setting state on unmounted component warning (happens whenever some async stuff is still loading but user navigates away from page before it finishes loading) that could cause memory leaks. React Query don't have this issue since it's global outside of React.

2021-04-12 00:08 UTC, darrenvong commented on app/frontend/src/features/contributorForm/ContributorForm.tsx
> +        setValue("location", info.location);
Don't these fields also exist in the form? It's better to set them as `defaultValue` on the form fields instead, otherwise React hook form warns about this

2021-04-12 00:08 UTC, darrenvong commented on app/frontend/src/features/contributorForm/ContributorForm.tsx
> +      setError(e.message);
Use mutation from React Query, again handles all of this error and loading state so slightly less boilerplate. You can more or less take the bit in the try-block and put it in the mutation but without needing the try-catch and setState/error stuff (react query catches error for us when things go wrong).

2021-04-12 00:08 UTC, darrenvong commented on app/frontend/src/features/contributorForm/ContributorForm.tsx
> +                    classes={{}}
```suggestion
```

2021-04-12 00:08 UTC, darrenvong commented on app/frontend/src/features/contributorForm/ContributorForm.tsx
> +    <>
This outer fragment `<>` is unnecessary since it's a single ternary

2021-04-12 00:08 UTC, darrenvong commented on app/frontend/src/features/contributorForm/ContributorForm.tsx
> +              <p>{ALREADY_FILLED_IN}</p>
Use `Typography` so it uses styles from the theme

2021-04-12 00:08 UTC, darrenvong commented on app/frontend/src/features/contributorForm/ContributorForm.tsx
> +                  <p>{SUCCESS_MSG}</p>
Use `Typography`

2021-04-12 00:08 UTC, darrenvong commented on app/frontend/src/features/contributorForm/ContributorForm.tsx
> +                      <p>{PLEASE_SIGN_UP}</p>
Same as above

2021-04-12 00:08 UTC, darrenvong commented on app/frontend/src/features/contributorForm/ContributorForm.tsx
> +                  <p>{FILL_IN_THE_FORM}</p>
Use `Typography`

2021-04-12 00:08 UTC, darrenvong commented on app/frontend/src/features/contributorForm/ContributorForm.tsx
> +                      <p>{YOU_CAN_ALSO}</p>
Use `Typography`

2021-04-12 00:08 UTC, darrenvong commented on app/frontend/src/features/contributorForm/ContributorForm.tsx
> +                      />
Better to conditionally not render this if user is authenticated rather than hiding it

2021-04-12 00:08 UTC, darrenvong commented on app/frontend/src/features/contributorForm/ContributorForm.tsx
> +                        <FormGroup aria-label="contribute">
Put the aria-label in constant file too

2021-04-12 00:08 UTC, darrenvong commented on app/frontend/src/features/contributorForm/ContributorForm.tsx
> +                  <p>{QUESTIONS_OPTIONAL}</p>
Use `Typography`

2021-04-12 00:08 UTC, darrenvong commented on app/frontend/src/features/Contribute.tsx
> +    // backgroundAttachment: "scroll, local",
```suggestion
    // backgroundAttachment: "scroll, local",
```
Remove if we don't need this?

2021-04-12 00:08 UTC, darrenvong commented on app/frontend/src/features/Contribute.tsx
> +    borderRadius: theme.shape.borderRadius / 3,
```suggestion
    borderRadius: theme.shape.borderRadius,
```
I've changed `borderRadius` value in the theme recently if you rebase with `develop` so don't need to divide by 3 anymore

2021-04-12 00:08 UTC, darrenvong commented on app/frontend/src/features/Contribute.tsx
> +    borderRadius: theme.shape.borderRadius / 3,
```suggestion
    borderRadius: theme.shape.borderRadius,
```

2021-04-12 00:08 UTC, darrenvong commented on app/frontend/src/features/contributorForm/ContributorForm.tsx
> +    const currentChoices = contribute.split(",").filter((v) => !!v);
What's wrong with the original form value that comes from react hook form's `onChange`? Couldn't the individual checkbox values be collected in `onSubmit` instead just before it gets sent to the fetch call rather than on every change?

2021-04-12 00:08 UTC, darrenvong commented on app/frontend/src/features/contributorForm/ContributorForm.tsx
> +                      />
```suggestion
                      <TextField
                        inputRef={register}
                        id="location"
                        margin="normal"
                        name="location"
                        label={LOCATION_LABEL}
                        helperText={LOCATION_HELPER}
                        fullWidth
                      />
```
Set the `defaultValue` prop on this (got a react-hook-form warning on this) with the result of `getContributorFormInfo`, should be accessible if using react query to do this once loaded.

2021-04-12 00:08 UTC, darrenvong commented on app/frontend/src/features/contributorForm/ContributorForm.tsx
> +            <>
Don't need this fragment either - single ternary again

2021-04-12 12:25 UTC, aapeliv commented on app/frontend/src/features/contributorForm/ContributorForm.tsx
> +    const currentChoices = contribute.split(",").filter((v) => !!v);
I have to do the filtering/concat on every change anyway, so I thought it'd be easier to just split/join here as well

2021-04-12 15:07 UTC, aapeliv commented on app/frontend/src/features/contributorForm/ContributorForm.tsx
> +        setValue("location", info.location);
I tried for quite a while to get this to work, but then couldn't figure out how to get these into the form without `setValue`, though I've moved stuff around

2021-04-12 15:08 UTC, aapeliv commented on app/frontend/src/features/contributorForm/ContributorForm.tsx
> +      setError(e.message);
Thanks, it is quite a lot easier!

2021-04-12 15:11 UTC, aapeliv commented
@darrenvong: I rebased on `develop`, fixed up the easy comments, and then refactored to use react query.

I was still having trouble setting the results from the first query (contributor form info endpoint) into the form, so I've still got it as hidden when logged in and using `setValue` in `onSuccess` in the react query query

2021-04-12 23:25 UTC, darrenvong requested changes
Very minor thing left, but this is a really great refactor overall 🎉

2021-04-12 23:25 UTC, darrenvong commented on app/frontend/src/features/contributorForm/ContributorForm.tsx
> +    return (await response.json()) as FormResponse;
```suggestion
    return response.json();
```
Unnecessary `await` if you are already returning a Promise - the caller (React Query) will await it correctly.

2021-04-12 23:25 UTC, darrenvong commented on app/frontend/src/features/contributorForm/ContributorForm.tsx
> +    const currentChoices = contribute.split(",").filter((v) => !!v);
Hmm yeah even doing it on submit is gonna be hacky and this is likely a one time thing people use, so happy to leave this as it is as this is still more readable than what I initially had in mind

2021-04-12 23:32 UTC, darrenvong approved these changes
Assume build succeeds as before

2021-04-12 23:38 UTC, merged