Minimum User Age
Couchers-org/couchers pull request #1038
Opened 2021-04-09 16:20 UTC by ceelo777

- Add minimum age requirement of 18 years for users
- Validate using birthdate
- Wrote test that passed for signups (checks whether birth date is valid)

2021-04-09 16:55 UTC, aapeliv requested changes
Looking good, some small nitpicks!

2021-04-09 16:55 UTC, aapeliv commented on app/backend/src/couchers/utils.py
> +    dt = now().date()
use `today_ = today()` (underscore to not overwrite the `today` object)

`dt` normally stands for datetime, but you only have a date

2021-04-09 16:55 UTC, aapeliv commented on app/backend/src/couchers/utils.py
> +def required_birthdate():
Maybe call this `minimum_allowed_birthdate` just to be super explicit

2021-04-09 16:55 UTC, aapeliv commented on app/backend/src/tests/test_auth.py
> +    with auth_api_session() as (auth_api, metadata_interceptor):
you can use the same session as above: you'll need to separate the `pytest.raises` into it's own `with` (just break it at the comma and create a new with block to put the above in, or have a look at how `pytest.raises` is used elsewhere

2021-04-09 16:55 UTC, aapeliv commented on app/backend/src/tests/test_auth.py
> +        )
please also add a test where the birthdate is like 17 years, not in the future but not yet 18

2021-04-09 16:55 UTC, aapeliv commented on app/backend/src/tests/test_auth.py
> +        )
please autoformat the code by running `isort . && black .` in `app`

2021-04-09 16:55 UTC, aapeliv commented on app/backend/src/couchers/servicers/auth.py
>                  context.abort(grpc.StatusCode.INVALID_ARGUMENT, errors.INVALID_BIRTHDATE)
please find the `INVALID_BIRTHDATE` string in errors and change it to something like `You must be at least 18 years old to sign up.`

2021-04-10 16:27 UTC, aapeliv requested changes
Ready to merge, but could you run the formatting commands one more time, there's a few formatting errors left!

2021-04-10 19:33 UTC, ceelo777 commented
> Ready to merge, but could you run the formatting commands one more time, there's a few formatting errors left!

Oops, forgot to format, my bad!

2021-04-10 22:24 UTC, aapeliv approved these changes
LGTM!

2021-04-10 23:20 UTC, merged