Reduce re-renders on edit location map
Couchers-org/couchers pull request #1052
Opened 2021-04-11 01:27 UTC by darrenvong

Reduces the number of re-renders quite significantly, and scope it to only the components that *needs* to be re-render to a smaller area (i.e. the radius slider). Previously, it was re-rendering on every character change when you update the display location and on every map move. See before and after video for the difference - the flashy squares is something from the React DevTools, shows quite nicely where things get re-rendered before/after this change.

**Before**
https://user-images.githubusercontent.com/13669362/114289116-58641980-9a6d-11eb-8d5d-d81f2927f6df.mov

**After**
https://user-images.githubusercontent.com/13669362/114289124-5dc16400-9a6d-11eb-8793-c273831ed751.mov

2021-04-11 01:31 UTC, darrenvong commented on app/frontend/src/features/profile/edit/EditProfile.tsx
> +            defaultValue=""
This is to stop the `react-hook-form` warning, even though we don't actually use the value of this field anyway...

2021-04-11 08:31 UTC, lucaslcode requested changes
This no longer updates the location field after a search

2021-04-11 11:37 UTC, darrenvong commented
Oops didn't realise that was a functionality, good catch. Fixed now!

2021-04-11 14:01 UTC, aapeliv commented
I had the `update` boolean on the `commit` to reduce the number of times we bubble the location back to the parent in cases when the user is between an action. That's unrelated to whether a re-draw/setDirty should happen or not.

1. When you select a search result for a new location, this now sends two updates, one with (new address, old coords) and then a second one with (new address, new coords), e.g. with a loc in NY and searching for London, `updateLocation` is called twice, with this history:

```
2: {"address":"New York","radius":1000,"lat":40.716740506264216,"lng":-74.00396063906874}
3: {"address":"London, England, United Kingdom","radius":1000,"lat":40.716740506264216,"lng":-74.00396063906874}
4: {"address":"London, England, United Kingdom","radius":1000,"lat":51.50025931937692,"lng":-0.1343511113528848}
```

Notice 3 has the coordinates from 2.

2. When I drag now it lags and calls `updateLocation` every move event, I'm not sure if lag is because of the continuous `updateLocation` calls or otherwise (this might make the parent redraw the child?). Before these changes, dragging the circle was buttery smooth and would fire off one update at the end of the drag/move.

Before (it's not laggy/tearing at all when not recording):

https://user-images.githubusercontent.com/2975660/114307234-c0862000-9aac-11eb-9e0f-d3ed6a40f0c2.mov

After (laggy/tearing even when not recording):

https://user-images.githubusercontent.com/2975660/114307231-be23c600-9aac-11eb-9928-44aad51162cc.mov

2021-04-11 21:18 UTC, darrenvong commented
Thanks for checking it over! I think the lag in Storybook is exaggerated (as I don't see this in the main page itself) and is mostly down to how you're printing the history as well, which is re-rendering **and** committing (i.e. changing the DOM) on every event so it's hammering the DOM.

Even though that's not a problem on the actual page, updating the ref state on every mousemove event is probably still an overkill even if it's not gonna cause re-renders, so I'll re-introduce the `update` flag you had before and that should fix the issue

2021-04-12 00:28 UTC, darrenvong commented
Should be addressed now 👍  also renamed that second param to `shouldUpdate` since seeing `updates` and `update` next to each other is a bit confusing...

2021-04-15 22:36 UTC, lucaslcode approved these changes

2021-04-15 23:13 UTC, merged