[MRG] Use GetHostRequest to standardize query and simplify testing
Couchers-org/couchers pull request #1122
Opened 2021-04-23 00:33 UTC by ShmuelTreiger

Realized a bunch of tests were missing. Also realized this was a simpler solution

2021-04-27 12:52 UTC, aapeliv requested changes

2021-04-27 12:52 UTC, aapeliv commented on app/backend/src/couchers/servicers/requests.py
> +    def GetHostRequest(self, request, context, pb=True):
Don't do this, please. It's confusing, this does two very different things now which is not good conceptually.

Just make a new helper function to grab the host request if you want to

2021-04-28 00:25 UTC, ShmuelTreiger commented
Testing _get_host_request_query directly would require faking context and I'm not sure how to do that. Instead I tested it indirectly, through GetHostRequest, but only once, instead of for each api call which uses the query.

2021-05-03 00:28 UTC, aapeliv requested changes

2021-05-03 00:28 UTC, aapeliv commented on app/backend/src/couchers/servicers/requests.py
> +    with session_scope() as session:
pass in the `session` as a variable so you don't need to do the `merge` stuff

2021-05-03 01:12 UTC, ShmuelTreiger commented
I should have changed this from merge, as whatever I do in #1163 will largely impact what I do here. I'm fact, I'll probably scrap this branch for that one.

2021-05-06 21:33 UTC, closed without merging