Beta sticker
Couchers-org/couchers pull request #1176
Opened 2021-05-03 14:32 UTC by aapeliv

Marketing people think we should make "betaness" more pronounced because we're light on features.

<img width="553" alt="Screen Shot 2021-05-03 at 10 27 37 am" src="https://user-images.githubusercontent.com/2975660/116889575-b57d6600-abfa-11eb-99fe-cc0990ce43ee.png">

**Frontend checklist**
- [ ] Formatted my code with `yarn format && yarn lint --fix`
- [ ] There are no warnings from `yarn lint`
- [ ] There are no console warnings when running the app
- [ ] Added any new components to storybook
- [ ] Added tests where relevant
- [ ] All tests pass
- [ ] Clicked around my changes running locally and it works
- [ ] Checked Desktop, Mobile and Tablet screen sizes

2021-05-03 15:08 UTC, lucaslcode requested changes
This pushes the close button off to the side on mobile.
We could possibly just get rid of the close button, since clicking off the sidebar closes it.

2021-05-03 15:08 UTC, lucaslcode commented on app/frontend/src/components/Navigation/Navigation.tsx
> +  const { logo, beta } = useAuthStyles();
Can you change this to `authClasses`

2021-05-03 15:08 UTC, lucaslcode commented on app/frontend/src/features/auth/useAuthStyles.ts
> +  },
How about doing `position: relative; left: -3rem; transform: rotate(45deg);`? Too cliché?

2021-05-10 22:49 UTC, aapeliv commented
<img width="353" alt="Screen Shot 2021-05-10 at 6 49 09 pm" src="https://user-images.githubusercontent.com/2975660/117733933-6ae28780-b1c0-11eb-8fa8-7695fd0624bd.png">

2021-05-10 22:55 UTC, aapeliv commented
<img width="300" alt="Screen Shot 2021-05-10 at 6 55 38 pm" src="https://user-images.githubusercontent.com/2975660/117734375-53f06500-b1c1-11eb-973c-642a6e810f77.png">

How about this one?

2021-05-11 17:53 UTC, aapeliv commented
Itsi was happy with the sticker on the logo.

2021-05-11 18:54 UTC, lucaslcode approved these changes
love it

2021-05-11 18:56 UTC, merged