Backend/feature/remove user from chat
Couchers-org/couchers pull request #1217
Opened 2021-05-10 17:20 UTC by Hassan-Mallah

**Backend checklist**
- [ ] Formatted my code by running `isort . && black .` in `app/backend`
- [ ] Added tests for any new code or added a regression test if fixing a bug
- [x] All tests pass
- [x] Run the backend locally and it works
- [ ] Added migrations if there are any database changes, rebased onto `develop` if necessary for linear migration history

**Frontend checklist**
- [ ] Formatted my code with `yarn format && yarn lint --fix`
- [ ] There are no warnings from `yarn lint`
- [ ] There are no console warnings when running the app
- [ ] Added any new components to storybook
- [ ] Added tests where relevant
- [ ] All tests pass
- [ ] Clicked around my changes running locally and it works
- [ ] Checked Desktop, Mobile and Tablet screen sizes

2021-05-10 17:40 UTC, aapeliv commented
Thanks, this is looking very good!

You should also send a message on that group chat saying an admin removed a user. You'll need to create a new message type in `MessageType` (in `models.py`) and then send it with `_add_message_to_subscription`, and add it to the protobuf enum and `_message_to_pb`. Once implemented in the frontend, it should then render as a message like "Hassan removed Aapeli."

2021-05-11 16:24 UTC, Hassan-Mallah commented
> Thanks, this is looking very good!
> 
> You should also send a message on that group chat saying an admin removed a user. You'll need to create a new message type in `MessageType` (in `models.py`) and then send it with `_add_message_to_subscription`, and add it to the protobuf enum and `_message_to_pb`. Once implemented in the frontend, it should then render as a message like "Hassan removed Aapeli."
thank you for the feedback, i'll do as u said. cheers

2021-05-12 06:11 UTC, Hassan-Mallah commented
@aapeliv hey,
I did changes as you said, i hope it's all correct :)
there's a test error with migration, i need to change these files as well?
cheers

2021-05-12 12:06 UTC, aapeliv requested changes
Great! Just a few minor comments.

I can push a migration file, if you're okay with that? The migration for this has to be done manually because alembic (the migration tool) doesn't detect changes in enums. Also happy for you to do it if you wish. Either way, you need to rebase onto `develop` (or merge `develop` into this) so we can build the migration on top of the latest schema.

2021-05-12 12:06 UTC, aapeliv commented on app/backend/src/couchers/models.py
> +    group_chat_user_removed = enum.auto()  # user is removed from group chat by amdin RemoveGroupChatUser
let's call this one `user_removed`

2021-05-12 12:06 UTC, aapeliv commented on app/pb/conversations.proto
> +message MessageContentRemoveGroupChatUser {
`MessageContentUserRemoved`

2021-05-12 12:06 UTC, aapeliv commented on app/backend/src/couchers/servicers/conversations.py
> +                context.abort(grpc.StatusCode.PERMISSION_DENIED, errors.ONLY_ADMIN_CAN_MAKE_ADMIN)
Please make new error strings in `couchers.errors` and use them here, these don't match the actual errors.

(Also two more instances below)

2021-05-13 03:48 UTC, Hassan-Mallah commented
@aapeliv Hey,
Thnks for the feedback :)
i did the changes, i think this time you do migration. Maybe next time i'll do it.
plz check. cheers

2021-05-13 19:53 UTC, aapeliv approved these changes
Great work, thanks!

I merged `develop` into here and added the migration. Next time, please remember to run `isort . && black .` in `//app/backend` to format the code.

You can merge as soon as the tests pass.

2021-05-14 11:14 UTC, merged

2021-05-14 11:16 UTC, Hassan-Mallah commented
great, thank u ;)