Backend/bugtool/1013 friend accept notification email
Couchers-org/couchers pull request #1438
Opened 2021-06-15 22:53 UTC by austinburnett

**Backend checklist**
- [ ] Formatted my code by running `isort . && black .` in `app/backend`
- [ ] Added tests for any new code or added a regression test if fixing a bug
- [ ] All tests pass
- [ ] Run the backend locally and it works
- [ ] Added migrations if there are any database changes, rebased onto `develop` if necessary for linear migration history

**Frontend checklist**
- [ ] Formatted my code with `yarn format && yarn lint --fix`
- [ ] There are no warnings from `yarn lint`
- [ ] There are no console warnings when running the app
- [ ] Added any new components to storybook
- [ ] Added tests where relevant
- [ ] All tests pass
- [ ] Clicked around my changes running locally and it works
- [ ] Checked Desktop, Mobile and Tablet screen sizes

2021-06-18 12:02 UTC, aapeliv requested changes
Great start! See comments

2021-06-18 12:02 UTC, aapeliv commented on app/backend/src/couchers/servicers/api.py
> +                send_friend_request_accepted_email(FriendRelationship)
`FriendRelationship` is the class name; you want to refer to the instance itself, `friend_request`

2021-06-18 12:02 UTC, aapeliv commented on app/backend/src/couchers/tasks.py
> +    friend_requests_link = urls
This should be a link to the person's profile who received the original friend req.

It should be `urls.profile_link(friend_relationship.to_user.username)` or something. You might need to add a `profile_link` function into `urls.py`. The right URL is in the frontend somewhere (see the comment at the top of `urls.py`)

2021-06-23 23:53 UTC, austinburnett commented
@aapeliv If you want you can just wait a couple more days to review this pr. I'm getting ready to make some more changes.

2021-06-30 15:09 UTC, aapeliv commented
I'm not sure what you've done, but this is now picking up a whole lot of unrelated commits and diff contains too much stuff not related to this PR. Can you message me on Slack so we can sort it out?

2021-06-30 17:16 UTC, aapeliv commented
Test failed: https://gitlab.com/couchers/couchers/-/jobs/1389893220#L153

2021-06-30 20:04 UTC, aapeliv commented on app/backend/templates/friend_request_accepted.md
> +subject: "{{ friend_relationship.to_user.name|couchers_escape }} accpeted your friend request!"
Typo in "accepted"

2021-07-20 08:06 UTC, aapeliv requested changes
Few tiny things left

2021-07-20 08:06 UTC, aapeliv commented on app/backend/src/couchers/urls.py
> +    return f"{config['BASE_URL']}/user/{user_name}"
Please rename `user_name` with `username`

2021-07-20 08:06 UTC, aapeliv commented on app/backend/src/tests/test_email.py
> +        #assert f"{config['BASE_URL']}/to_user.name" in html
`assert f"{config['BASE_URL']}/user/{to_user.username}" in plain`

2021-07-20 08:06 UTC, aapeliv commented on app/backend/src/couchers/tasks.py
> +    friend_requests_link = urls.user_link(friend_relationship.to_user.username)
Should be renamed to `user_link`

2021-07-21 21:36 UTC, aapeliv commented
Tests are still failing: https://gitlab.com/couchers/couchers/-/jobs/1439757892

2021-08-02 19:09 UTC, aapeliv approved these changes
LGTM!

2021-08-03 20:58 UTC, merged