Map Circle Warning
Couchers-org/couchers pull request #1456
Opened 2021-06-20 00:41 UTC by JGibbsWork

Updated signup to include a confirmation dialogue wrapper warning about the circle surrounding the address. Not sure if we want to create a barrier for signing up, but it did seem like a more direct way to solve the problem for new users. Also added text below the map when editing your profile. More than happy to change either accordingly.

**Frontend checklist**
- [ ] Formatted my code with `yarn format && yarn lint --fix`
- [ ] There are no warnings from `yarn lint`
- [ ] There are no console warnings when running the app
- [ ] Added any new components to storybook
- [ ] Added tests where relevant
- [ ] All tests pass
- [ ] Clicked around my changes running locally and it works
- [ ] Checked Desktop, Mobile and Tablet screen sizes

2021-06-20 08:58 UTC, lucaslcode commented
@AllhandsNoFeet thoughts?

2021-06-22 09:07 UTC, lucaslcode requested changes
Seems good to me for now.

Could you change `ConfirmationDialogWrapper.tsx` so it has a prop that lets you choose between "Okay" and "Yes" as the 'accept button'. Like `confirmButtonLabel`

I also noticed that if there's a server error ("you must be 18 yo to sign up"), it is hard to notice because the submit button is at the bottom of a long form.

Could you add this to `signup.tsx`

```
  useEffect(() => {
    if (authState.error) window.scroll({ top: 0, behavior: "smooth" });
  }, [authState.error]);
```

2021-06-22 09:08 UTC, lucaslcode commented on app/frontend/src/components/EditLocationMap.tsx
> +      <Typography color="secondary" gutterBottom={true}>
```suggestion
      <Typography variant="body2" gutterBottom>
```
I think that's sufficient

2021-06-23 22:24 UTC, JGibbsWork commented
Cool on it!

2021-06-24 21:25 UTC, lucaslcode requested changes
Tiny thing but looks good!

2021-06-24 21:25 UTC, lucaslcode commented on app/frontend/src/components/ConfirmationDialogWrapper.tsx
> +            {confirmButtonLabel ? confirmButtonLabel : "Yes"}
Better move the default to a constant (sorry)

2021-06-25 08:18 UTC, lucaslcode approved these changes
👍

2021-06-27 16:11 UTC, aapeliv commented
Is this ready to merge? If so, feel free to merge it yourself @JGibbsWork

2021-06-28 17:47 UTC, merged

2021-06-28 17:47 UTC, JGibbsWork commented
Sorry about that! All set now!