Countries => regions visited / lived in
Couchers-org/couchers pull request #1470
Opened 2021-06-21 11:15 UTC by rbrishabh

fixes #1464

hey @ShmuelTreiger, how does this look? Let me know if this needs any changes! Thanks

2021-06-21 12:35 UTC, lucaslcode commented
Thanks! Did you check all the tests are passing with `yarn test`?

2021-06-21 12:35 UTC, lucaslcode commented on app/frontend/src/features/constants.ts
> +export const COUNTRIES_VISITED = "Regions I've Visited";
It would be better to change the constant name too.

2021-06-21 20:15 UTC, ShmuelTreiger commented
In about.tsx, "country" is used in a bunch of variable names. Do those need changing? (I don't know much about the front end)

2021-06-21 20:43 UTC, rbrishabh commented
hey @lucaslcode! How does this look now?
Thanks1

2021-06-22 08:39 UTC, lucaslcode requested changes
Please run `yarn lint --fix` to sort imports

2021-06-23 06:43 UTC, rbrishabh commented
Sure!

2021-06-23 06:47 UTC, rbrishabh commented
done! @lucaslcode Feel free to review when you have time!

2021-06-24 21:19 UTC, lucaslcode approved these changes
Thanks for your contribution!

2021-06-24 21:19 UTC, merged