comment count break fix
Couchers-org/couchers pull request #1516
Opened 2021-06-27 14:57 UTC by sadikekin

closes #1483 

**Frontend checklist**
- [X] Formatted my code with `yarn format && yarn lint --fix`
- [X] There are no warnings from `yarn lint`
- [X] There are no console warnings when running the app
- [X] Added any new components to storybook
- [X] Added tests where relevant
- [] All tests pass
- [X] Clicked around my changes running locally and it works
- [X] Checked Desktop, Mobile and Tablet screen sizes

<img width="1679" alt="Screenshot 2021-06-27 at 16 52 15" src="https://user-images.githubusercontent.com/25348720/123549231-61a97c00-d768-11eb-93e1-4dcce71d410f.png">

2021-06-27 20:33 UTC, lucaslcode commented
Hi @sadikekin!
I think we should take this opportunity to make it look acceptable on mobile.
Right now, it has it's own column on the right and on narrow screens, the main text of the card gets really squished up
Can you move the comment count text so it is on it's own line underneath everything else? Also make sure the margins are suitable for the new position. And the count text can be the smaller "body2" instead of "body1" variant.

Now: 
![image](https://user-images.githubusercontent.com/32044095/123558558-cb3c8100-d78e-11eb-839a-ff8056d9f25f.png)

Instead, something like this:
![image](https://user-images.githubusercontent.com/32044095/123558605-16ef2a80-d78f-11eb-9593-3c4241b441e1.png)

2021-06-27 20:33 UTC, lucaslcode requested changes
see above

2021-06-30 20:00 UTC, sadikekin commented
![Uploading Screenshot 2021-06-30 at 21.56.55.png…]()

2021-06-30 20:00 UTC, sadikekin commented
<img width="424" alt="Screenshot 2021-06-30 at 21 56 55" src="https://user-images.githubusercontent.com/25348720/124023754-9d557780-d9ee-11eb-9ef6-5b557da93a7e.png">

2021-06-30 21:11 UTC, lucaslcode requested changes
Looks great! I think we don't need this right margin at all now, since we have the card padding.

2021-06-30 21:11 UTC, lucaslcode commented on app/frontend/src/features/communities/discussions/DiscussionCard.tsx
> +    marginInlineEnd: theme.spacing(1),
```suggestion
```

2021-07-01 07:47 UTC, lucaslcode approved these changes
Thanks!!

2021-07-01 07:47 UTC, merged