Add username into account settings screen
Couchers-org/couchers pull request #1648
Opened 2021-07-15 14:12 UTC by aapeliv

This is a quick fix so we can point users to the account settings where it says very clearly what their username is. This is needed for the community builder form.

**Backend checklist**
- [ ] Formatted my code by running `autoflake -r -i --remove-all-unused-imports src && isort . && black .` in `app/backend`
- [ ] Added tests for any new code or added a regression test if fixing a bug
- [ ] All tests pass
- [ ] Run the backend locally and it works
- [ ] Added migrations if there are any database changes, rebased onto `develop` if necessary for linear migration history

**Frontend checklist**
- [ ] Formatted my code with `yarn format && yarn lint --fix`
- [ ] There are no warnings from `yarn lint`
- [ ] There are no console warnings when running the app
- [ ] Added any new components to storybook
- [ ] Added tests where relevant
- [ ] All tests pass
- [ ] Clicked around my changes running locally and it works
- [ ] Checked Desktop, Mobile and Tablet screen sizes

2021-07-15 14:30 UTC, kalvdans approved these changes, later dismissed
lgtm!

2021-07-15 19:05 UTC, lucaslcode submitted a review, later dismissed
Optional change, but I think it's a good idea.

2021-07-15 19:05 UTC, lucaslcode commented on app/frontend/src/features/auth/constants.tsx
> +  "Your username is set when you create your account. There is currently no way to change your username, sorry.";
```suggestion
  "Your username is set when you create your account.";
```

2021-07-15 19:06 UTC, lucaslcode requested changes
Build errors from tests/storybook

2021-07-16 22:04 UTC, lucaslcode approved these changes

2021-07-16 22:04 UTC, merged