Events part 6: edit event page
Couchers-org/couchers pull request #1862
Opened 2021-08-23 03:45 UTC by darrenvong

This is probably the final piece for the MVP of #541. It looks more or less identical to the "create event page" since they share the same form UI. This has been intentional with how I put the form UI into its own component.

**Frontend checklist**
- [x] Formatted my code with `yarn format && yarn lint --fix`
- [x] There are no warnings from `yarn lint`
- [x] There are no console warnings when running the app
- [ ] Added any new components to storybook
- [x] Added tests where relevant
- [x] All tests pass
- [x] Clicked around my changes running locally and it works
- [ ] Checked Desktop, Mobile and Tablet screen sizes

2021-08-24 00:06 UTC, darrenvong commented on app/frontend/package.json
> +    "test": "TZ=UTC react-scripts test",
Wish I found this out earlier for ensuring the timezone used is the same across our computer and CI. The timezone mock thing has been causing me pain for a while as it'd error with something about unknown Date constructor as soon as I need to interact with the date inputs/dayjs.

This seems like the only solution that works by changing the test timezone to UTC with fake timers to "fix" the current date so our test data would work/pass date validation etc

2021-08-25 06:51 UTC, thdk commented on app/frontend/src/features/communities/events/EventForm.test.tsx
> +    jest.setSystemTime(new Date("2021-08-01 00:00"));
Move to beforeAll on line 211? Else adding a second test in this describe method will still have this system date. Or not yet have this system date if the second test was executed before this test that sets the system date.

2021-08-25 06:51 UTC, thdk commented on app/frontend/src/features/communities/events/CreateEventPage.test.tsx
> +    jest.setSystemTime(new Date("2021-08-01 00:00"));
Can be removed? Same is set in beforeEach

2021-08-25 18:51 UTC, lucaslcode commented on app/frontend/src/features/communities/events/CreateEventPage.tsx
> +    </EventForm>
Not a big deal but to me this seems more opaque than a required `submitButton` prop.

2021-08-25 18:55 UTC, lucaslcode requested changes
Changing an event from offline to online doesn't move it to the global community.

Also, there's a backend bug - changing something other than the date gives an error about not being allowed to have overlapping occurrences.

2021-08-25 19:07 UTC, darrenvong commented on app/frontend/src/features/communities/events/EventForm.test.tsx
> +    jest.setSystemTime(new Date("2021-08-01 00:00"));
This is specifically placed here (after the location click from `LocationAutocomplete` on line 225-226) since it has the same problem as the other test - that the `msw` server doesn't respond when the fake timers are on. I probably could leave a comment here too.

As for the concern that this will break things if we add more tests here, I could move the `jest.useRealTimers()` to an `afterEach` instead so it will correctly reset the timer after every test

2021-08-25 19:10 UTC, darrenvong commented
> Changing an event from offline to online doesn't move it to the global community.

I think that's also a backend flaw. Currently `UpdateEventReq` doesn't allow a `parentCommunityId` to be specified, so the API will need to be updated to allow that too. Otherwise the current workaround would be an additional API call to `TransferEvent`

2021-08-25 21:59 UTC, darrenvong commented on app/frontend/src/features/communities/events/CreateEventPage.tsx
> +    </EventForm>
I thought about using an explicitly named prop than using `children`, but since this is literally appearing at the bottom of the form, it fits naturally enough with composition for me in this case.

2021-08-26 01:36 UTC, darrenvong commented
Also moving the event from online to offline to a different community (going from what you said) is also technically impossible at the moment, as all events will originate from the global community in those cases and there's no way for the frontend to figure out which community a location belongs to... but I guess that logic's kinda broken anyway since we are allowing events to be created in locations that might not match with where the community say it is.

So maybe it doesn't make much sense to move an event to the global community because it's going from offline to online? Or are we allowing it anyway as a non-reversible thing?

2021-08-29 16:39 UTC, lucaslcode approved these changes

2021-08-29 21:58 UTC, merged