[#1884] Frontend - label of text input does not hide when start entering value
Couchers-org/couchers pull request #1905
Opened 2021-09-01 19:33 UTC by goskan93

closes #1884

**Frontend checklist**
- [ ] Formatted my code with `yarn format && yarn lint --fix`
- [ ] There are no warnings from `yarn lint`
- [ ] There are no console warnings when running the app
- [ ] Added any new components to storybook
- [ ] Added tests where relevant
- [ ] All tests pass
- [ ] Clicked around my changes running locally and it works
- [ ] Checked Desktop, Mobile and Tablet screen sizes

2021-09-05 23:23 UTC, darrenvong commented
Is this ready, or is it meant to be still a draft/WIP @goskan93?

2021-09-06 12:40 UTC, goskan93 commented
Hey, the code is ready, but I didn't have time to do frontend checklist to be sure everything is fine. I will do it tomorrow

2021-09-08 01:04 UTC, darrenvong commented
> when do yarn run test, I get ''TZ' is not recognized as an internal or external command,
> operable program or batch file.' and I don't know what to do about it

Are you on Windows? It'll be because the command is only Unix friendly 😅  and on Windows there's a slightly different syntax for setting environment variables.

I cloned your branch over anyway just so CI can run and the failing tests aren't related to your change so it's all good!

2021-09-08 01:31 UTC, darrenvong requested changes

2021-09-08 01:31 UTC, darrenvong commented on app/frontend/src/components/EditLocationMap.tsx
> +          onBlur={() => setShrinkLabel(false)}
In this `onBlur` as it is, if you go to the map, select a location, then focus on this input and click away (which triggers a blur event), this will unshrink the label and make it go behind the text:
![Screenshot 2021-09-08 at 02 26 55](https://user-images.githubusercontent.com/13669362/132431091-f07df05c-244f-48f7-a98b-20842d629956.png)

I think it needs an additional check to see if the input field has a value or not before deciding whether to shrink the label or not. I think checking `locationDisplayRef.current.value` is probably the best way, unless you can get the value within the `onBlur` event handler

2021-09-08 18:24 UTC, goskan93 commented
@darrenvong I created another PR, because I had some problem with resolving conflicts. Please check here https://github.com/Couchers-org/couchers/pull/1937

2021-09-08 18:24 UTC, closed without merging