Automatically convert links within user messages
Couchers-org/couchers pull request #2124
Opened 2021-10-22 05:53 UTC by wbruntra

Adding a component to render user messages containing links with `<a>` tags instead of plaintext.

This actually turns out to be surprisingly complicated, and would be even harder if you really wanted to be sure to cover all possible URLs while avoiding any false positives. So I decided to try for something "good enough" instead.

URL regex modified from: https://github.com/kevva/url-regex

**Web frontend checklist**
- [x] Formatted my code with `yarn format && yarn lint --fix`
- [x] There are no warnings from `yarn lint`
- [x] There are no console warnings when running the app
- [ ] Added any new components to storybook
- [x] Added tests where relevant
- [x] All tests pass
- [x] Clicked around my changes running locally and it works
- [ ] Checked Desktop, Mobile and Tablet screen sizes

2021-10-22 15:34 UTC, lucaslcode requested changes
Looks good, and thanks for tests!

Comments on events and discussions are actually Markdown, not plain text as I thought, but do you want to enable autolinks by adding `extendedAutolinks: true,` to both `components/Markdown.tsx` and `components/MarkdownEditor/MarkdownEditor.tsx` in the `ToastUIEditor` constructor? (That's the markdown library we're using).
Also, you can clone the repo and make a branch next time, and you'll get our automated checks/previews etc.

2021-10-22 15:34 UTC, lucaslcode commented on app/web/src/components/Linkify.tsx
> +function Linkify(props: LinkifyProps) {
Nitpick - we usually dereference props

2021-10-22 15:34 UTC, lucaslcode commented on app/web/src/components/Linkify.tsx
> +    }
I think returning `null` is preferred when not rendering anything (though this is indeed valid)

2021-10-24 08:21 UTC, wbruntra commented on app/web/src/components/Linkify.tsx
> +function Linkify(props: LinkifyProps) {
I'm not the best on terminology so to be sure I understand what you're looking for, you mean to use `{ text }` instead of `props` and `props.text`?

2021-10-24 09:18 UTC, wbruntra commented
@lucaslcode I believe this addresses all of your specific comments. You referenced `components/MarkdownEditor/MarkdownEditor.tsx`, which does not exist, so I changed `MarkdownInput.tsx`. Let me know if that's not the file you intended.

> Also, you can clone the repo and make a branch next time, and you'll get our automated checks/previews etc.

Okay, will do

2021-10-24 09:25 UTC, wbruntra commented
I'll just note here that the extended links feature on Toast UI recognizes links a bit differently from my implementation. Specifically, they require the link start with either `www` or a protocol, which I didn't do, although that's definitely a good way of avoiding false positives. But honestly, you see a lot of false positives on e.g. twitter, which makes me think it isn't really that big of a deal. And being a frugal person, I am a fan of non-`www` subdomains. It works well enough.it doesn't have to be perfect.

2021-10-24 11:37 UTC, lucaslcode commented on app/web/src/components/Linkify.tsx
> +function Linkify(props: LinkifyProps) {
Yep!

2021-10-24 11:37 UTC, lucaslcode commented
> it doesn't have to be perfect

I agree! If people complain about false-positives we can always change it later.

2021-10-24 12:38 UTC, lucaslcode requested changes
This is great, sorry for forgetting to mention this one thing last time. Then it's ready to merge.

2021-10-24 12:38 UTC, lucaslcode commented on app/web/src/components/Linkify.tsx
> +        <a
If you use `<Link>` from material ui (not from react-router-dom), it will get correct styling from the theme automatically and you won't need a className

2021-10-25 05:17 UTC, wbruntra commented on app/web/src/components/Linkify.tsx
> +        <a
Ah, very good, thanks

2021-10-25 09:12 UTC, lucaslcode approved these changes
Great! Go ahead and merge it :)

2021-10-25 09:58 UTC, merged