insert link to leave reference in notification email
Couchers-org/couchers pull request #2128
Opened 2021-10-23 21:03 UTC by sndrr

.. to make it easier to leave feedback for other users and make Couchers grow with one less click.

Closes #1671

**Backend checklist**
- [ ] Formatted my code by running `autoflake -r -i --remove-all-unused-imports src && isort . && black .` in `app/backend`
- [ ] Added tests for any new code or added a regression test if fixing a bug
- [ ] All tests pass
- [ ] Run the backend locally and it works
- [ ] Added migrations if there are any database changes, rebased onto `develop` if necessary for linear migration history

**Web frontend checklist**
- [ ] Formatted my code with `yarn format && yarn lint --fix`
- [ ] There are no warnings from `yarn lint`
- [ ] There are no console warnings when running the app
- [ ] Added any new components to storybook
- [ ] Added tests where relevant
- [ ] All tests pass
- [ ] Clicked around my changes running locally and it works
- [ ] Checked Desktop, Mobile and Tablet screen sizes

2021-10-23 21:03 UTC, sndrr commented
First issue, work in progress.

2021-10-26 00:30 UTC, aapeliv requested changes
Sorry for the slow review. Besides the small comment, I think this is good to go!

2021-10-26 00:30 UTC, aapeliv commented on app/backend/templates/host_reference.md
> +
I don't think the button works inline, it'll be rendered as a block like this

![Screenshot from 2021-10-25 20-28-23](https://user-images.githubusercontent.com/2975660/138788739-84e4bde5-d02f-4712-ae51-76f2bf1aef61.png)

Also I don't think the button will work in plaintext emails. Maybe something like this?

```
{% if html %}
{{ button("Write a reference", leave_reference_link)|couchers_safe }}

Alternatively, click the following link: {{ link(leave_reference_link, html)|couchers_safe }}.
{% else %}
<{{ leave_reference_link|couchers_escape }}>
{% endif %}
```

2022-01-06 15:56 UTC, aapeliv commented
Continued at #2308

2022-01-06 15:56 UTC, closed without merging