Web/feature/multi line text field
Couchers-org/couchers pull request #2303
Opened 2022-01-04 23:29 UTC by dieterpankratz

This PR transforms the TextInputField to a single line input field which grows to multiple lines for long messages. 
It affects input fields under the following route:
`/messages/chats/:id`

**Backend checklist**
- [ ] Formatted my code by running `autoflake -r -i --remove-all-unused-imports src && isort . && black .` in `app/backend`
- [ ] Added tests for any new code or added a regression test if fixing a bug
- [ ] All tests pass
- [ ] Run the backend locally and it works
- [ ] Added migrations if there are any database changes, rebased onto `develop` if necessary for linear migration history

**Web frontend checklist**
- [ X] Formatted my code with `yarn format && yarn lint --fix`
- [ X] There are no warnings from `yarn lint`
- [ ] There are no console warnings when running the app
- [ ] Added any new components to storybook
- [ ] Added tests where relevant
- [ X] All tests pass
- [X ] Clicked around my changes running locally and it works
- [X ] Checked Desktop, Mobile and Tablet screen sizes

2022-01-04 23:31 UTC, dieterpankratz commented
@lucaslcode I am not sure if /messages/chats/:id is the only place where this input behavior is needed. Could you confirm it?

2022-01-05 01:15 UTC, lucaslcode commented
There's also /messages/request/:id

2022-01-05 17:37 UTC, dieterpankratz commented
I applied the new input field behavior on the /messages/request/:id page. However, there is that 'Cancel' button that seems a bit misplaced. Is there a design somewhere where I can check how to position that cancel button?

<img width="1173" alt="Screen Shot 2022-01-05 at 6 35 55 PM" src="https://user-images.githubusercontent.com/39704300/148262836-67f97aa6-f6ab-445d-9b73-ecb8d147d2ae.png">

2022-01-06 16:14 UTC, lucaslcode commented
The cancel is referring to the host request - it would start off as an Accept and Reject button.

This page was redesigned in the mockups and we haven't made the changes in the app yet. In the updated design, the request response buttons are under the last message: 
![image](https://user-images.githubusercontent.com/32044095/148413820-e7befde7-05e1-4f9f-9826-b90c4430a2bc.png)

That might be a bit of a challenge with the way the message pages work at the moment (they were some of the first pages we did, so the code is a bit less.... mature).

So the moral is, I think for this PR just give it some margin so it's not right next to the text box :)

2022-01-07 19:33 UTC, dieterpankratz commented
I added some margin and I guess this PR is ready to be reviewed @lucaslcode :)

2022-01-08 05:13 UTC, lucaslcode requested changes
Looks good! One thing:

For closed requests, the "This request is closed..." message now overflows on mobile as it's quite long. I think we need to move it out of the placeholder and either add it on to the end of the message list, or above the send field (see what you think is better).

Relevant files/lines would be: `HostRequestView.tsx:215` is the list of messages where you could add a "fake" message if the request is closed, and `HostRequestSendField.tsx:119` has the `isRequestClosed` logic which could be moved into a `utils.ts` file in the same folder.

Also, when typing a really long message, the list doesn't stay scrolled to the bottom. But I suspect fixing that is quite complicated (we already have some somewhat complex logic to scroll to the bottom (or not) when sending a message I believe) so let's not worry about that for now.

2022-01-09 11:52 UTC, dieterpankratz commented
Hi @lucaslcode for some reason I can't login in develop anymore. 
I am using Option 2: Target the preview api and backend. 
When I use the URL, like 
http://localhost:3000/login?token=x2I3WKq1...
The login page just gets refreshed but I don't sign in. 
Have you faced this issue before?

2022-01-09 13:12 UTC, lucaslcode commented
That's strange. Can you log in at next.couchershq.org?
Also try clearing all your cookies.
We recently merged the NextJS refactor, you may want to rebase your PR (that shouldn't affect login, though). 
If that doesn't work, send me an email.

2022-01-17 22:45 UTC, closed without merging