Landing page and platform merge
Couchers-org/couchers pull request #2362
Opened 2022-01-15 11:48 UTC by aapeliv

First cut at merging landing site and app.

**Web frontend checklist**
- [ ] Formatted my code with `yarn format && yarn lint --fix`
- [ ] There are no warnings from `yarn lint`
- [ ] There are no console warnings when running the app
- [ ] Added any new components to storybook
- [ ] Added tests where relevant
- [ ] All tests pass
- [ ] Clicked around my changes running locally and it works
- [ ] Checked Desktop, Mobile and Tablet screen sizes

2022-01-15 13:17 UTC, aapeliv commented
Old:
<img width="1680" alt="Screen Shot 2022-01-15 at 3 16 26 pm" src="https://user-images.githubusercontent.com/2975660/149623105-1f2fd826-283f-49b0-bdd9-7db3652f3a40.png">


New:
<img width="1680" alt="Screen Shot 2022-01-15 at 3 16 32 pm" src="https://user-images.githubusercontent.com/2975660/149623107-797e48a3-28f4-4dce-b945-7197fc01f1da.png">


Old:
<img width="1680" alt="Screen Shot 2022-01-15 at 3 16 48 pm" src="https://user-images.githubusercontent.com/2975660/149623115-f9bcc76d-6233-47c5-8b94-74eaccb44710.png">

New:
<img width="1680" alt="Screen Shot 2022-01-15 at 3 16 52 pm" src="https://user-images.githubusercontent.com/2975660/149623117-33e294d0-f402-4f50-a949-b1cb8dd8283a.png">

2022-01-15 14:41 UTC, aapeliv commented
Logged out menus:
<img width="428" alt="Screen Shot 2022-01-15 at 4 41 20 pm" src="https://user-images.githubusercontent.com/2975660/149625817-d07e96b1-5f25-43d6-b458-5c8eba3c434b.png">
<img width="427" alt="Screen Shot 2022-01-15 at 4 41 15 pm" src="https://user-images.githubusercontent.com/2975660/149625824-96fed7c1-1972-4c16-a78b-511fe7fcb90b.png">
<img width="1677" alt="Screen Shot 2022-01-15 at 4 41 02 pm" src="https://user-images.githubusercontent.com/2975660/149625825-30584f76-ddd4-4928-b195-1f622ccb23f6.png">

2022-01-15 15:57 UTC, aapeliv commented
Team page:

old:
<img width="1678" alt="Screen Shot 2022-01-15 at 5 56 09 pm" src="https://user-images.githubusercontent.com/2975660/149628493-235e81fb-4c6a-46f6-9beb-1664c93b79f2.png">

new:
<img width="1680" alt="Screen Shot 2022-01-15 at 5 56 16 pm" src="https://user-images.githubusercontent.com/2975660/149628495-ef1a0f90-6241-453f-96e9-ab8dad981433.png">

2022-01-15 16:31 UTC, aapeliv commented
@lucaslcode: I can't get the meta tags to work properly. They're all just the same "Couchers.org Beta" in the vercel preview and when doing `next build && next start` locally

2022-01-15 18:31 UTC, aapeliv commented
OK, these pages are straight up just not being SSRd, I don't know what I'm doing wrong or if I'm just very confused here!

2022-01-15 22:09 UTC, lucaslcode reviewed
Great work! I will look properly later. Your `getStaticPaths` needs to be async and await the slugs function.

2022-01-16 11:27 UTC, lucaslcode reviewed
Some general stuff:
- There's a bug in AppRoutes so these pages are statically rendering a loader instead of the page. I think line 79 `!isMounted || (isPrivate && !isAuthenticated)` should be `(!isMounted && isPrivate) || (isPrivate && !isAuthenticated)
- Are you using markdown-it instead of our markdown component because ours doesn't work with ssr? Maybe we should replace that one with markdown-it.
- The tag colours look weird, but I can't offer any suggestions (except for maybe removing them completely?)

2022-01-21 10:28 UTC, aapeliv commented
> There's a bug in AppRoutes so these pages are statically rendering a loader instead of the page. I think line 79 `!isMounted || (isPrivate && !isAuthenticated)` should be `(!isMounted && isPrivate) || (isPrivate && !isAuthenticated)`

It works well (on these pages) and is server side rendered (turning off JS) if I just replace that logic with `false` (aka never show the spinner). It seems to be something to do with `isMounted`, I don't know what that does.

2022-01-21 12:02 UTC, aapeliv commented
>     * Are you using markdown-it instead of our markdown component because ours doesn't work with ssr? Maybe we should replace that one with markdown-it.

I'm just using it because it was used on Vue and I wanted everything to be as similar as possible.

>     * The tag colours look weird, but I can't offer any suggestions (except for maybe removing them completely?)

I think we can leave it for now. The tag colors match the boxes on the current landing page when you scroll down.

2022-01-22 13:20 UTC, aapeliv commented
@lucaslcode: I've implemented the landing page now. It works as follows:

1. if you're logged in, `/` shows you the dashboard
2. if you're logged out, `/` shows the landing page as currently on couchers.org

I'm out of juice on this at the moment. I know it's a pretty crap PR in terms of code quality...

Random stuff:
* I don't know why Vercel is failing, for all I can see it should work
* It's missing a little "scroll down for more" arrow on the landing page
* I tweaked some of the login/signup CSS. It seems it's quite a bit of a mess at the moment (and I doubt I made it any better).
* The landing page AppRoute thing is a mess: if logged in it should be `variant = "standard"`, but if logged out, it should be `full-screen`. This is the `currentVariant` mess.
* This does not follow the UI/UX designs for the landing page. I don't think they're quite ready and thought out yet, and I don't have the skill/patience/juice to build that. So I ported over our existing landing page and made-do. This is (in my opinion) a small regression visually and in UI/UX, but I think it's worth it and we can tweak it further later. I just want to get rid of the awful vue landing site.
* SSR still doesn't work, it's something to do with `isMounted`, if I just comment that out it works fine (but flashes the wrong type of page at times)
* I changed the navbar to be `fixed` and added padding. This gives us pages that are the right height (e.g. login/signup) with just `100vh`, and allows the landing page above-fold to just be `100vh` and then have a nice page below.
* The landing page isn't set up fully with translations yet, I ran out of juice. But it's not a huge thing since I added the `landing` translation component. The translation keys are also a tad bit of a mess in like duplicates between `auth`, etc.
* I bastardized `BasicForm` to put it on the landing page. After you fill it in it'll redirect to `/signup` (but it flashes first). If you've already filled it in it and you goon the landing page again it shows a button to finish signing up.

2022-01-31 22:34 UTC, lucaslcode reviewed
This is notes for myself

2022-01-31 22:34 UTC, lucaslcode commented on app/web/components/AppRoute.tsx
> +  variant?: "standard" | "full-screen" | "full-width" | "landing";
Check

2022-01-31 22:34 UTC, lucaslcode commented on app/web/components/IconText.tsx
> +  text: ReactNode;
Don't include textbody for type=string

2022-01-31 22:34 UTC, lucaslcode commented on app/web/components/Navigation/LoggedInMenu.tsx
> +        onClose={() => setMenuOpen(() => false)}
(false)

2022-01-31 22:34 UTC, lucaslcode commented on app/web/components/Navigation/Navigation.tsx
> +const loggedOutDrawerMenu = (data: MenuGenData): Array<MenuItemProps> => [
rename data

2022-01-31 22:34 UTC, lucaslcode commented on app/web/components/Navigation/Navigation.tsx
> +      position="fixed"
check margins

2022-01-31 22:34 UTC, lucaslcode commented on app/web/features/Index.tsx
> +  if (isAuthenticated) {
Change to a rewrite

2022-01-31 22:34 UTC, lucaslcode commented on app/web/features/auth/locales/en.json
> +    "create_account": "Create an account"
rename? global?

2022-01-31 22:34 UTC, lucaslcode commented on app/web/components/AppRoute.tsx
> +    padding: "64px 0 0 0",
Make navbar effect clearer/use variable

2022-01-31 22:34 UTC, lucaslcode commented on app/web/features/auth/useAuthStyles.ts
> +    // justifyContent: "flex-end",
rm

2022-01-31 22:34 UTC, lucaslcode commented on app/web/features/landing/LandingPage.tsx
> +  },
MUI?

2022-01-31 22:34 UTC, lucaslcode commented on app/web/features/markdown/MarkdownPage.tsx
> +const mkd = new markdown();
Make issue to replace other md renderer or do here if easy

2022-01-31 22:34 UTC, lucaslcode commented on app/web/features/markdown/MarkdownPage.tsx
> +    maxWidth: "769px",
container mui

2022-01-31 22:34 UTC, lucaslcode commented on app/web/features/team/Team.tsx
> +    maxWidth: "769px",
mui

2022-01-31 22:34 UTC, lucaslcode commented on app/web/features/team/Team.tsx
> +    height: "96px",
no magic

2022-01-31 22:34 UTC, lucaslcode commented on app/web/features/team/team.json
> +    "location": "London, United Kingdom",
change

2022-02-01 09:54 UTC, lucaslcode commented
This is basically done but needs some checking

2022-02-01 09:55 UTC, lucaslcode commented
Note that the landing page/dashbiard redirect middleware doesn't work on preview, because the cookie domain is .couchershq.org, so web browsers don't include it in the request.

2022-02-03 11:00 UTC, lucaslcode approved these changes
This should be good once all checks are green

2022-02-03 11:04 UTC, lucaslcode requested changes
Wait the home page still isn't pre-rendered

2022-02-03 11:08 UTC, lucaslcode approved these changes
Okay NOW when checks are green

2022-02-03 16:16 UTC, merged