error message on DonationsBox
Couchers-org/couchers pull request #2466
Opened 2022-01-31 12:43 UTC by Zenpanic

better error message when donating decimals or negative numbers

closes #2432 
when entering a negative number or a decimal number on the donation page, and submitting the form, the "Assertion error" message is replaced by "Whole numbers only, please!".

**Web frontend checklist**
- [X] Formatted my code with `yarn format && yarn lint --fix`
- [X] There are no warnings from `yarn lint`
- [X] There are no console warnings when running the app
- [X] All tests pass
- [X] Clicked around my changes running locally and it works
- [X] Checked Desktop, Mobile and Tablet screen sizes

2022-02-01 00:05 UTC, darrenvong requested changes

2022-02-01 00:05 UTC, darrenvong commented on app/web/features/donations/DonationsBox.tsx
> +        {error && <Alert severity="error">{error.message !== "Assertion failed" ? error.message : "Whole numbers only, please!"}</Alert>}
I don't think we should rely on the "Assertion failed" message to always mean the user has typed in a non positive integer, as this would end up showing the wrong message if the backend API gets modified/extended with more assertions in the future.

Since we can read the `amount` on form submission, it's more reliable to intercept there as a custom validation rule to check that the number is non-negative and a whole number instead with React hook form.

2022-02-01 00:05 UTC, darrenvong commented on app/web/features/donations/DonationsBox.tsx
> +        {error && <Alert severity="error">{error.message !== "Assertion failed" ? error.message : "Whole numbers only, please!"}</Alert>}
Also, can you please move this to `/app/web/features/donations/locale/en.json`, name the translation key `amount_validation_error` within the `donations_box` object and read the message here from there with the `t` function? We are trying to move away from hardcoded messages so they can be translated to multiple languages.

2022-02-01 11:23 UTC, Zenpanic commented on app/web/features/donations/DonationsBox.tsx
> +        {error && <Alert severity="error">{error.message !== "Assertion failed" ? error.message : "Whole numbers only, please!"}</Alert>}
Thanks for the feedback, @darrenvong I'm on it.

2022-02-02 00:39 UTC, darrenvong requested changes
Can you run `yarn format` and `yarn lint` on the code as well to make sure the code is formatted properly and there aren't any linting issues? I can see the code formatting looks a bit misaligned at least 😅  

And thanks for the French translation too 🇫🇷

2022-02-02 14:20 UTC, Zenpanic commented
It should be alright now :)

2022-02-03 01:02 UTC, darrenvong requested changes
Sorry, hopefully the last thing!

Forgot to mention but in future, you can run `yarn typecheck` to catch this same problem too, since the [development build doesn't check for type checking issues](https://github.com/vercel/next.js/issues/14997). I will look into adding that into the checklist or our get started doc... 😅

2022-02-03 01:02 UTC, darrenvong commented on app/web/features/donations/DonationsBox.tsx
> +  const checkForValidAmount: boolean = (amount: number) => {
```suggestion
  const checkForValidAmount = (amount: number) => {
```
This type error is failing the build

2022-02-03 10:42 UTC, Zenpanic commented on app/web/features/donations/DonationsBox.tsx
> +  const checkForValidAmount: boolean = (amount: number) => {
Thanks for your patience and the advice! I'll keep that in mind for the next issue. I've fixed the code and tried it, hopefuly it's all good now!

2022-02-03 22:26 UTC, darrenvong approved these changes

2022-02-03 22:26 UTC, merged