doc: Instructions to update the docker grpc image
Couchers-org/couchers pull request #2526
Opened 2022-02-07 10:49 UTC by papeldeorigami

Add information on how to update the docker image that create the local protocol buffers.

2022-02-07 16:00 UTC, aapeliv submitted a review, later dismissed
Ah, thank you!

2022-02-07 16:28 UTC, darrenvong commented on app/readme.md
> +### How to update the protocol buffers
```suggestion
### How to update the protocol buffers compiler
```
Very minor nitpick as the above steps already update the protocol buffers, but errors because of an updated compiler.

2022-02-07 16:29 UTC, darrenvong commented on app/readme.md
> +### How to update the protocol buffers
In fact, I'll just commit the suggestion to save more round trips of this being merged :p

2022-02-07 16:30 UTC, darrenvong approved these changes, later dismissed

2022-02-09 03:36 UTC, aapeliv requested changes, later dismissed
Actually, I think you can get around this by using the `--pull always` flag on the `docker run` command; like this:

```sh
docker run --pull always --rm -w /app -v $(pwd):/app registry.gitlab.com/couchers/grpc ./generate_protos.sh
```

2022-02-09 12:50 UTC, lucaslcode approved these changes, later dismissed

2022-02-10 01:58 UTC, darrenvong commented on app/readme.md
> +### How to update the protocol buffers
```suggestion
### How to update the protocol buffers compiler
```

2022-02-10 01:59 UTC, darrenvong approved these changes

2022-02-10 02:00 UTC, merged