Refactor: finish i18n for communities
Couchers-org/couchers pull request #2595
Opened 2022-02-20 12:15 UTC by papeldeorigami

Replace all constants in the communities with translation keys

This is part of #2351 

**Web frontend checklist**
- [ ] Formatted my code with `yarn format && yarn lint --fix`
- [ ] There are no warnings from `yarn lint`
- [ ] There are no console warnings when running the app
- [ ] Added any new components to storybook
- [ ] Added tests where relevant
- [ ] All tests pass
- [ ] Clicked around my changes running locally and it works
- [ ] Checked Desktop, Mobile and Tablet screen sizes

2022-02-22 02:10 UTC, darrenvong requested changes
Mostly looking good! I tried to be not perfectionist this time so we get this done, but some key names are just so literal and bad that I had to suggest some changes 🙃 ... along with some minor issues with this

2022-02-22 02:10 UTC, darrenvong commented on app/web/components/Footer/Footer.tsx
> +            </FooterLink>
Since it looks like this string is used only by the footer, I think maybe it's best to move this string into the global namespace (even though it's sadly a bit counter-intuitive). Otherwise, this doesn't work with server side rendering without having to include the `communities` namespace on all pages which may defeat the point of "lazy loading" them by specifying the list of namespaces to load with `serverSideTranslations`.

See screenshot below where it shows `show_all_events` key as is :(

![Screenshot 2022-02-22 at 01 42 49](https://user-images.githubusercontent.com/13669362/155047904-1df84fef-cf80-406b-8320-70b248f3d6a4.png)

2022-02-22 02:10 UTC, darrenvong commented on app/web/features/communities/CommunityPage/InfoPageSection.tsx
> +        {t("communities:general_information")}
```suggestion
        {t("communities:community_info_page_title")}
```

2022-02-22 02:10 UTC, darrenvong commented on app/web/features/communities/EditCommunityInfoPage.tsx
> +            <PageTitle>{t("communities:edit_local_info")}</PageTitle>
```suggestion
            <HtmlMeta title={t("communities:edit_info_page_title")} />
            <PageTitle>{t("communities:edit_info_page_title")}</PageTitle>
```

2022-02-22 02:10 UTC, darrenvong commented on app/web/features/communities/EditCommunityInfoPage.tsx
> +                {t("communities:community_page_updated")}
```suggestion
                {t("communities:edit_info_page_success_message")}
```

2022-02-22 02:10 UTC, darrenvong commented on app/web/features/communities/discussions/Comment.tsx
> +            {t("communities:reply")}
I think this might be worth extracting to the global namespace, since it seems like quite a generic, standalone string that can be re-used elsewhere (e.g. in a host request, message etc)

2022-02-22 02:10 UTC, darrenvong commented on app/web/features/communities/discussions/CommentForm.tsx
> +            <Button onClick={onClose}>{t("communities:close")}</Button>
```suggestion
            <Button onClick={onClose}>{t("global:close")}</Button>
```
And then perhaps we can delete "close" in the communities namespace altogether for generic strings like these.

2022-02-22 02:10 UTC, darrenvong commented on app/web/features/communities/discussions/DiscussionCard.tsx
> +                }`}
I think this whole message should be incorporated into the `comments` key with interpolation rather than partially left in the code

2022-02-23 09:37 UTC, papeldeorigami commented on app/web/features/communities/CommunityPage/InfoPageSection.tsx
> +        {t("communities:general_information")}
resolved with e9b4f2080b535d445ab05c9705853198a691b4a2

2022-02-23 09:38 UTC, papeldeorigami commented on app/web/components/Footer/Footer.tsx
> +            </FooterLink>
resolved with eb09d47028d38d22070300ad68f7cecf669352ad

2022-02-23 09:38 UTC, papeldeorigami commented on app/web/features/communities/EditCommunityInfoPage.tsx
> +            <PageTitle>{t("communities:edit_local_info")}</PageTitle>
resolved with 4363555d1bd4e38cd3dd212b20fddcba090db4c5

2022-02-23 09:39 UTC, papeldeorigami commented on app/web/features/communities/EditCommunityInfoPage.tsx
> +                {t("communities:community_page_updated")}
resolved with 9e296a9105dd25aa0e1d1b36cb5d34aa312256ab

2022-02-23 09:40 UTC, papeldeorigami commented on app/web/features/communities/discussions/CommentForm.tsx
> +            <Button onClick={onClose}>{t("communities:close")}</Button>
resolved with 1e062af047a61340e4061de589b87be6c5d5cba3 (sorry for the wrong commit message, I wrote reply instead of close)

2022-02-23 09:41 UTC, papeldeorigami commented on app/web/features/communities/discussions/Comment.tsx
> +            {t("communities:reply")}
Resolved with 90d1605b2f378fb3a4cd709c3b28ff7decab0ab9

2022-02-23 09:46 UTC, papeldeorigami commented on app/web/features/communities/discussions/DiscussionCard.tsx
> +                }`}
Resolved with 398b829cf87293f2d7e1b0bf7dc2b390829f9683

2022-02-28 23:37 UTC, darrenvong approved these changes

2022-03-01 00:33 UTC, darrenvong commented
I'm gonna merge this in to open up more of the platforms to be translated 🚀

2022-03-01 00:33 UTC, merged