fix: message input not visible in mobile screens
Couchers-org/couchers pull request #2671
Opened 2022-03-08 03:03 UTC by darrenvong

On mobile screens, the chat input is not visible until you scroll so this PR aims to fix it.

The fix itself is a bit hacky, since the height of the address bar could be subject to change between OS versions. But honestly, I can't think of a more simpler way without either:
- Slapping the 100% height back everywhere again (since the use of `100vh` is the thing that caused issues - on mobile, `vh` doesn't seem to take into account the address bar as taking up space...), so that we can use `100%` in place of `100vh`
- Read the real view height in JS and set the height of the container accordingly (seems a bit overkill to me)

**Web frontend checklist**
- [x] Formatted my code with `yarn format && yarn lint --fix`
- [x] There are no warnings from `yarn lint`
- [ ] There are no console warnings when running the app
- [ ] Added any new components to storybook
- [ ] Added tests where relevant
- [x] All tests pass
- [x] Clicked around my changes running locally and it works (although admittedly, this is one where the simulated tool fails since it doesn't have the address bar covering up some pixels)
- [x] Checked Desktop, Mobile and Tablet screen sizes

2022-03-09 12:33 UTC, lucaslcode requested changes
This needs browser sniffing as per that article, or there's wasted space on other mobile browsers

2022-03-12 22:51 UTC, darrenvong commented
> This needs browser sniffing as per that article, or there's wasted space on other mobile browsers

I thought that too initially, but after testing on mobile Firefox too:
![Screenshot_20220312-224752](https://user-images.githubusercontent.com/13669362/158037664-8e85db30-3eed-4cd0-8ddd-5a398f8e0e68.jpg)

It seems like the problem is not only on Chromium browsers, so I thought it's safe to apply it across the board for narrow screens. Might need some testing on iOS Safari (I don't have an iPhone) but I think the thing mentioned in the article will include them too since they are also WebKit based.

2022-03-12 22:53 UTC, darrenvong commented
And it only gets applied up to 600px screen width, so I think it's fairly safe that tablets will be large enough such that they won't see the problem as I don't know many tablets with narrower screens than that

2022-03-12 23:34 UTC, lucaslcode approved these changes

2022-03-13 02:53 UTC, merged