Add grpc web dev tools
Couchers-org/couchers pull request #378
Opened 2020-12-04 14:23 UTC by aapeliv

I found this great dev tool, it shows you the requests in a "JSON-like" way, works on FF and Chrome:

https://github.com/SafetyCulture/grpc-web-devtools

Screenshot:

<img width="738" alt="Screen Shot 2020-12-04 at 9 20 57 am" src="https://user-images.githubusercontent.com/2975660/101174751-492e1480-3612-11eb-9fb6-4e4e89011808.png">

Do we want this? Any downsides? We can of course add a config var to enable/disable?

2020-12-04 14:32 UTC, aapeliv commented
Install from <https://github.com/SafetyCulture/grpc-web-devtools>.

You can try it out here <https://frontend-feature-grpc-web-dev-tools--frontend.preview.coucher.org/>

2020-12-04 22:09 UTC, darrenvong commented
Not tried yet but I like the look of this! I think as long it's only loading that in dev mode, I don't see any problems with it, since that's how the React and Redux dev tools work too :+1:

2020-12-07 00:50 UTC, darrenvong requested changes
Personally happy to merge this once we ensured it only loads during "development" mode!

2020-12-07 00:50 UTC, darrenvong commented on app/frontend/src/service/client.ts
> +]);
```suggestion
if (process.env.NODE_ENV === "development") {
  grpcWebTools([
    apis.api,
    apis.bugs,
    apis.sso,
    apis.conversations,
    apis.auth,
    apis.requests,
    apis.jail,
  ]);
}
```

2020-12-07 01:13 UTC, darrenvong approved these changes

2020-12-07 01:14 UTC, merged