Fix issue 4335
Couchers-org/couchers pull request #4504
Opened 2024-06-30 18:44 UTC by alexxmhuang

I think this closes #1234? Not sure if there are more changes I need to make. 

**Backend checklist**
- [ ] Formatted my code by running `ruff check --select I --fix . && ruff check . && ruff format .` in `app/backend`
- [ ] Added tests for any new code or added a regression test if fixing a bug
- [ ] All tests pass
- [ ] Run the backend locally and it works
- [ ] Added migrations if there are any database changes, rebased onto `develop` if necessary for linear migration history

**Web frontend checklist**
- [ ] Formatted my code with `make format`
- [ ] There are no warnings from `make lint`
- [ ] There are no console warnings when running the app
- [ ] Added any new components to storybook
- [ ] Added tests where relevant
- [ ] All tests pass
- [ ] Clicked around my changes running locally and it works
- [ ] Checked Desktop, Mobile and Tablet screen sizes

2024-06-30 19:08 UTC, aapeliv requested changes
Looking good, see the few small notes.

2024-06-30 19:08 UTC, aapeliv commented on app/web/.env.development
> -NEXT_PUBLIC_COUCHERS_ENV=preview
You shouldn't commit these changes

2024-06-30 19:08 UTC, aapeliv commented on app/backend/src/couchers/servicers/admin.py
> +        return self.AddAdminNote(request, context)
The formatter is complaining, you should run
```
ruff check --select I --fix . && ruff check . && ruff format .
```

2024-06-30 19:08 UTC, aapeliv commented
> I think this closes #1234?

That's the wrong issue it seems

2024-06-30 19:39 UTC, alexxmhuang commented
OK i fixed them

2024-07-06 22:49 UTC, aapeliv requested changes
Some tests are still failing. Please re-run the formatter.

2024-07-16 02:29 UTC, merged