WIP: fix empty discussion post in events communities
Couchers-org/couchers pull request #5073
Opened 2024-10-28 23:10 UTC by katemoser

Checklists not yet completed, because I am not yet done!

**Backend checklist**
- [ ] Formatted my code by running `ruff check --select I --fix . && ruff check . && ruff format .` in `app/backend`
- [ ] Added tests for any new code or added a regression test if fixing a bug
- [ ] All tests pass
- [ ] Run the backend locally and it works
- [ ] Added migrations if there are any database changes, rebased onto `develop` if necessary for linear migration history

**Web frontend checklist**
- [ ] Formatted my code with `yarn format`
- [ ] There are no warnings from `yarn lint --fix`
- [ ] There are no console warnings when running the app
- [ ] Added any new components to storybook
- [ ] Added tests where relevant
- [ ] All tests pass
- [ ] Clicked around my changes running locally and it works
- [ ] Checked Desktop, Mobile and Tablet screen sizes

2024-10-28 23:12 UTC, katemoser commented
Sorry, half my comment seems to have been deleted, I think I filled out the template wrong!

This is for #4172 , added front end validation and backend check as well. Started writing tests but would like to chat with someone for 15-20 minutes about how to best write tests for this!

2024-10-29 03:22 UTC, nabramow commented
> Sorry, half my comment seems to have been deleted, I think I filled out the template wrong!
> 
> This is for #4172 , added front end validation and backend check as well. Started writing tests but would like to chat with someone for 15-20 minutes about how to best write tests for this!

Leaving a comment here about tests in case we don't overlap soon!

Code looks great so far.

Another good frontend test would be to make a new test file `CommentForm.test.tsx` (since no one is testing that component yet) and test that when the comment form is empty or only filled with whitespace characters, tabs, etc. and user hits submit, it doesn't call the `postReply` function. You could do this by mocking the service like:

```javascript
const postReplyMock = service.thread.postReply as jest.Mock;
```

Then check it wasn't called in the individual test:

```javascript
expect(postReplyMpck).not.toHaveBeenCalled();
```

For backend, you probably wanna add a test case in `test_threads.py`, the `def test_threads_errors(db)` function looks right. Probably you'd make the content in the arguments equal to `""` and then check the right error showed. Looks like there's some similar functions in there you could base it on.

Instructions for testing locally on the backend are in `app/backend/readme.md`. You can run tests for only one function like `pytest test_threads.py::test_threads_errors` (path might be different to folder).

2024-10-29 17:46 UTC, bakeiro commented on app/backend/src/couchers/errors.py
> +INVALID_COMMENT = "You cannot post an empty comment."
don't we have translations for the backend errors? (not related with this PR, generally asking)

2024-11-25 20:34 UTC, aapeliv reviewed
Backend looks good to me!

2024-12-15 15:57 UTC, bakeiro commented
I've run the `lint` & `format` to make the build pass, @aapeliv says the backend look good... guess it's fine to merge? (and to leave the PR in this state...)

2024-12-15 16:13 UTC, bakeiro submitted a review, later dismissed
LGTM

2024-12-15 16:19 UTC, bakeiro submitted a review, later dismissed

2024-12-16 04:08 UTC, nabramow reviewed
Hey I am unapproving it as gitlab tests are failing.

2024-12-16 04:09 UTC, nabramow requested changes
Sorry now I am unapproving.

2025-01-22 05:17 UTC, nabramow commented on app/web/features/communities/EditCommunityInfoPage.tsx
> -              )}
I moved the error functionality to be within the MarkdownInput since we are passing the errorText in multiple components already but not displaying it.

Now that that's done I can remove this extra error logic.

2025-01-22 12:43 UTC, aapeliv approved these changes, later dismissed
LGTM, two small optional things

2025-01-22 12:43 UTC, aapeliv commented on app/web/components/MarkdownInput/MarkdownInputNoSSR.tsx
> +    marginTop: "8px",
Should this be in `theme.spacing`?

2025-01-22 12:43 UTC, aapeliv commented on app/backend/src/couchers/servicers/threads.py
> +        if request.content.strip() == "":
Might be good to do `content = request.content.strip()`, then use `content` below on lines 124/126. That way it'll strip the surrounding whitespace from the comments/replies.

2025-01-23 02:44 UTC, merged