Basic 404 page
Couchers-org/couchers pull request #514
Opened 2021-01-20 02:18 UTC by a-ch-chu

Fulfils issue #336.

2021-01-20 02:20 UTC, a-ch-chu commented
Graphic based off [this image](https://openclipart.org/detail/11252/couch) from OpenClipart. A vector version would probably be preferable.

2021-01-20 02:22 UTC, aapeliv commented
> Graphic based off [this image](https://openclipart.org/detail/11252/couch) from OpenClipart. A vector version would probably be preferable.

Thanks! For posterity: Open Clipart says this is licensed under CC0 (public domain).

2021-01-21 00:00 UTC, lucaslcode commented
Is this still a WIP? Also next time you can make a branch in our repo, that way the CI will work and we can preview without checking out the branch.

2021-01-27 22:28 UTC, lucaslcode requested changes
I'm going to be annoying and say we should make everything *Page even though there are a few which aren't. Otherwise ready to merge!

2021-01-27 22:28 UTC, lucaslcode commented on app/frontend/src/AppRoutes.tsx
> +import NotFound from "./features/NotFoundPage";
```suggestion
import NotFoundPage from "./features/NotFoundPage";
```

2021-01-27 22:28 UTC, lucaslcode commented on app/frontend/src/AppRoutes.tsx
> +        <NotFound />
```suggestion
        <NotFoundPage />
```

2021-01-27 22:28 UTC, lucaslcode commented on app/frontend/src/features/NotFoundPage.tsx
> +export default function NotFound() {
```suggestion
export default function NotFoundPage() {
```

2021-02-03 08:35 UTC, lucaslcode submitted a review, later dismissed

2021-02-05 20:34 UTC, lucaslcode approved these changes

2021-02-05 20:34 UTC, merged