Add flag button to discussions/comments
Couchers-org/couchers pull request #5393
Opened 2024-12-25 00:12 UTC by aapeliv

Continues from abandoned #5321, closes #5122.

**Web frontend checklist**
- [ ] Formatted my code with `yarn format`
- [ ] There are no warnings from `yarn lint --fix`
- [ ] There are no console warnings when running the app
- [ ] Added any new components to storybook
- [ ] Added tests where relevant
- [ ] All tests pass
- [ ] Clicked around my changes running locally and it works
- [ ] Checked Desktop, Mobile and Tablet screen sizes

2024-12-25 09:25 UTC, jesseallhands approved these changes
LGTM! Though maybe have someone who codes take a look.

EDIT: I found a problem. See comment below.

2024-12-25 09:33 UTC, jesseallhands requested changes
Clicking on the flag on comments works , but if you click on the flag on the discussion card while on the community page, the flag doesnt work. It just takes you to the discussion where you can read the comments.

2025-01-05 17:46 UTC, nabramow commented
Hey @aapeliv, to fix this, in the `FlagButton` component, add this:

- line 108 change to a div like this: `    <div onClick={handleFlagButtonClick}>` (change closing div too)
- Add this function:

```javascript
  const handleFlagButtonClick = (event: { preventDefault: () => void }) => {
    event.preventDefault();
  };
```

That will prevent the `DiscussionCard` click event from triggering when the `FlagButton` is clicked.

2025-01-15 04:27 UTC, nabramow approved these changes, later dismissed
This is working well for me now! Tested the discussions, comments, replies and the original flag on the user profile page.

2025-01-15 22:38 UTC, aapeliv commented
This PR has been done too poorly. (Posted from GH CLI). Updated.

2025-01-16 02:17 UTC, merged