Annotate markdown fields in API and database
Couchers-org/couchers pull request #598
Opened 2021-02-08 07:33 UTC by kalvdans

Patch that sprinkles "CommonMark without images" everywhere, feel free to thumbsdown if you think it pollutes the files rather than helping.

Not sure if references are to allowed to be Markdown formatted or just a string of words.

2021-02-08 08:49 UTC, lucaslcode commented
Maybe this should wait until after #529 to avoid merge conflicts

2021-02-08 14:41 UTC, aapeliv requested changes

2021-02-08 14:41 UTC, aapeliv commented on app/backend/src/couchers/models.py
> +    # the CommonMark-compliant message text if not control
I believe the group chat messages are plaintext. Is that right @lucaslcode?

2021-02-08 14:41 UTC, aapeliv commented on app/backend/src/couchers/models.py
> +    text = Column(String, nullable=True)  # CommonMark without images
The reference also is currently plaintext, I think

2021-02-08 14:41 UTC, aapeliv commented on app/pb/api.proto
> +  string text = 4;  // CommonMark without images
As above

2021-02-08 14:41 UTC, aapeliv commented on app/pb/api.proto
> +  string text = 3;  // CommonMark without images
As above

2021-02-08 14:41 UTC, aapeliv commented on app/pb/conversations.proto
> +    MessageContentText text = 4;  // CommonMark without images
As above

2021-02-23 23:33 UTC, aapeliv commented
> Maybe this should wait until after #529 to avoid merge conflicts

#529 has now been merged.

2021-02-24 00:58 UTC, kalvdans commented
> #529 has now been merged.

Thanks for the reminder! Merged latest develop and fixed your comments.

2021-02-24 01:17 UTC, aapeliv requested changes

2021-02-24 01:17 UTC, aapeliv commented on app/pb/conversations.proto
> +    MessageContentText text = 4;  // CommonMark without images
I think this is still plain text

2021-02-24 19:39 UTC, aapeliv approved these changes
LGTM!

2021-02-24 19:51 UTC, merged