feat: allow users to paste csv into profileTagInput
Couchers-org/couchers pull request #614
Opened 2021-02-10 20:28 UTC by Tay0108

Closes #262.

If you have any ideas how to do it better please let me know because I'm not 100% satisfied with it 😅

2021-02-10 22:53 UTC, lucaslcode approved these changes, later dismissed
Optional changes

2021-02-10 22:53 UTC, lucaslcode commented on app/frontend/src/features/profile/ProfileTagInput.tsx
> +  allowCsv,
```suggestion
  allowCsv = true,
```
If it's true by default, you don't have to add it to each field (I can't see any reason we wouldn't want it most of the time).

2021-02-10 22:53 UTC, lucaslcode commented on app/frontend/src/features/profile/ProfileTagInput.tsx
> +            setPendingValue(Array.from(uniqueValues));
```suggestion
            setPendingValue(Array.from(
              //remove whitespace-only values
              uniqueValues.filter((value) => !/^\s*$/.test(value))
            ));
```
This is extra but good to have in there

2021-02-11 22:33 UTC, Tay0108 commented
Btw. there is a reason that I didn't merge it yet - I've found a bug (existing on current develop version) that if you press enter on an empty input it removes entries that were already there. Working on fix.

2021-02-12 00:22 UTC, lucaslcode requested changes
Looks good but run `yarn format`, there's some funny indentation. (Personally I set up vs code to run prettier every time I save so I don't have to do that.)

2021-02-12 00:31 UTC, Tay0108 commented
> Looks good but run `yarn format`, there's some funny indentation. (Personally I set up vs code to run prettier every time I save so I don't have to do that.)

I was sure I did that! Also, shouldn't we have some .prettierrc file? 

Usually I use key shortcuts to do that but for some reason they are not working for me on this project in both VS Code & Webstorm.

2021-02-12 09:10 UTC, lucaslcode approved these changes
> shouldn't we have some .prettierrc file

We could but we're just using the defaults atm

2021-02-12 09:11 UTC, merged