Backend/bugfix/birthdate in past
Couchers-org/couchers pull request #637
Opened 2021-02-15 04:32 UTC by OmerBaddour

Modified **auth.py** to now also check that the birthdate entered upon sign up is in the past.

Retained the same form of try/except that was previously only used to check the form of the birthdate. This makes sense to me because the `is_valid_date()` function simply yields **True/False**. Invoking this function, checking for **True**, and then converting the string to a **datetime** instance is less straightforward than simply trying to convert the string to a **datetime** instance (especially since the **datetime** instance is needed by the database in the valid case).

Note: my code does not account for timezones. I prioritized simplicity and readability over this level of accuracy.

Note: also fixed a typo in a comment for unrelated code, since the comment is used to generate documentation.

2021-02-15 13:52 UTC, aapeliv requested changes

2021-02-15 13:52 UTC, aapeliv commented on app/backend/src/couchers/servicers/auth.py
> +                    context.abort(grpc.StatusCode.INVALID_ARGUMENT, errors.INVALID_BIRTHDATE)
This should be moved outside the try-catch block. The block is there to catch any errors in date formatting. What you've added shouldn't raise a ValueError.

Also, please use the `now()` function from `couchers.utils`. It's timezone aware and should be used everywhere. Timezone bugs are a pain.

2021-02-15 15:14 UTC, aapeliv commented on app/backend/src/couchers/servicers/auth.py
> +            if utc.localize(birthdate) >= now():
Need to import pytz, then do `pytz.UTC.localize(...)`

2021-02-15 15:28 UTC, aapeliv commented
LGTM, contingent on tests passing

2021-02-15 15:28 UTC, aapeliv approved these changes, later dismissed
LGTM, contingent on tests passing

2021-02-18 00:42 UTC, OmerBaddour commented
Added birthdate test. Passes all tests.

2021-02-18 00:43 UTC, aapeliv approved these changes

2021-02-18 00:50 UTC, aapeliv commented
Closes #274

2021-02-18 04:31 UTC, merged