Add required id prop to TextField component
Couchers-org/couchers pull request #681
Opened 2021-02-23 14:24 UTC by ineswq

Closes #590 

TODO:
- [x]  Add required `id` prop to TextField component
- [x] Add unique id to instances of TextField in other components

2021-02-23 16:58 UTC, lucaslcode reviewed
Thanks so much!
Looks good ~~but I will check the build tonight since our CI checks don't run on forks. ~~ ✔️ 

Also I don't recognize your username, if you want to join the slack, send me an email (it should be in the git logs) (:

2021-02-23 16:58 UTC, lucaslcode commented on app/frontend/src/features/auth/login/UsernameForm.tsx
> +          id="username/email"
```suggestion
          id="username-email"
```
I think the original is indeed valid html5 but having a slash isn't conventional I think.

2021-02-23 21:58 UTC, lucaslcode requested changes
Just that one thing!
Also, let me know if you'd like to to deal with the merge conflicts.

2021-02-24 10:43 UTC, ineswq commented
Thank you for your review! I committed that one change. :) 
Could you or someone with write access resolve the merge conflicts?

2021-02-24 10:54 UTC, lucaslcode commented
Will do!

2021-02-24 10:59 UTC, Tay0108 commented on app/frontend/src/components/TextField.tsx
> +interface TextfieldProps extends OutlinedTextFieldProps {
This can just use TextFieldProps from material-ui since we have parametrized variant now

2021-02-24 10:59 UTC, Tay0108 commented on app/frontend/src/components/TextField.tsx
> +}: Omit<TextfieldProps, "variant">) {
This can just use TextFieldProps from material-ui since we have parametrized variant now

2021-02-24 12:11 UTC, Tay0108 commented
Made PR with resolved merge conflicts: https://github.com/Couchers-org/couchers/pull/693

2021-02-24 13:00 UTC, lucaslcode commented
This had to be in a new PR in order to merge, but your commits are there! Thanks!

2021-02-24 13:00 UTC, closed without merging