Enforce id requirement in TextField component
Couchers-org/couchers pull request #711
Opened 2021-02-26 14:25 UTC by ineswq

Closes issue #590 , follows up PR #681

2021-02-26 18:19 UTC, darrenvong requested changes
Looks good apart from the nitpick on formatting I saw. It's worth running `yarn format` in future to fix these first before pushing anything :)

2021-02-26 18:19 UTC, darrenvong commented on app/frontend/src/components/TextField.tsx
> +import { BaseTextFieldProps } from "@material-ui/core/TextField"
```suggestion
import { BaseTextFieldProps } from "@material-ui/core/TextField";
```

2021-02-26 18:19 UTC, darrenvong commented on app/frontend/src/components/TextField.tsx
> +   onChange?: TextFieldProps["onChange"]
```suggestion
   onChange?: TextFieldProps["onChange"];
```

2021-03-01 09:01 UTC, ineswq commented
Will do, thank you!

2021-03-02 00:24 UTC, darrenvong approved these changes

2021-03-02 00:24 UTC, merged