[WIP] Diff schema created by models.py and migrations
Couchers-org/couchers pull request #885
Opened 2021-03-31 22:28 UTC by kalvdans

I managed to get some rudimentary sorting of pg_dump output, but it still displays some differences.

```diff
@@ -33,25 +33,6 @@

 
 COMMENT ON EXTENSION unaccent IS 'text search dictionary that removes accents';
 
-
---
--- Name: alembic_version alembic_version_pkc; Type: CONSTRAINT; Schema: public; Owner: chn
---
-
-ALTER TABLE ONLY public.alembic_version
-    ADD CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num);
-
-
---
--- Name: alembic_version; Type: TABLE; Schema: public; Owner: chn
---
-
-CREATE TABLE public.alembic_version (
-    version_num character varying(32) NOT NULL
-);
-
-
-ALTER TABLE public.alembic_version OWNER TO chn;
 
 --
 -- Name: background_jobs id; Type: DEFAULT; Schema: public; Owner: chn
@@ -1267,6 +1248,13 @@

 
 
 --
+-- Name: idx_users_geom; Type: INDEX; Schema: public; Owner: chn
+--
+
+CREATE INDEX idx_users_geom ON public.users USING gist (geom);
+
+
+--
 -- Name: initiated_uploads fk_initiated_uploads_initiator_user_id_users; Type: FK CONSTRAINT; Schema: public; Owner: chn
 --
 
@@ -2298,7 +2286,7 @@

 --
 
 CREATE TABLE public.sessions (
-    api_calls integer DEFAULT 0 NOT NULL,
+    api_calls integer NOT NULL,
     created timestamp with time zone DEFAULT now() NOT NULL,
     deleted timestamp with time zone,
     expiry timestamp with time zone DEFAULT (now() + '90 days'::interval) NOT NULL,
@@ -2356,17 +2344,17 @@

 CREATE FUNCTION public.slugify(text text) RETURNS text
     LANGUAGE sql IMMUTABLE STRICT
     AS $_$
-    SELECT regexp_replace(
+SELECT regexp_replace(
+  regexp_replace(
+    substring(
       regexp_replace(
-        substring(
-          regexp_replace(
-            lower(unaccent("text")),
-            '[^a-z0-9\-_]+', '-', 'gi'
-          ) from 0 for 64
-        ), '\-+$', ''
-      ), '^\-', ''
-    );
-    $_$;
+        lower(unaccent("text")),
+        '[^a-z0-9\\-_]+', '-', 'gi'
+      ) from 0 for 64
+    ), '\-+$', ''
+  ), '^\-', ''
+);
+$_$;
 
 
 ALTER FUNCTION public.slugify(text text) OWNER TO chn;
```

2021-03-31 22:33 UTC, kalvdans commented
Who would guess postgres stores actual text for functions and not the parsed AST.... :/

2021-04-01 01:58 UTC, aapeliv commented
> Who would guess postgres stores actual text for functions and not the parsed AST.... :/

How else would you support arbitrary languages? You can write postgres functions in python with pl/python O.o

2021-04-01 02:01 UTC, aapeliv commented
I'll look more tomorrow. It looks like CI doesn't have pg_dump

2021-04-02 02:45 UTC, aapeliv commented
@kalvdans: you're the debian guy. It seems buster doesn't have postgres 13 utilities in their packages;

https://packages.debian.org/search?keywords=postgres+client&searchon=names&suite=buster&section=all

We're using the 13 server, and postgres docs state "pg_dump cannot dump from PostgreSQL servers newer than its own major version; it will refuse to even try" (https://www.postgresql.org/docs/current/app-pgdump.html)

2021-04-02 08:11 UTC, kalvdans commented
> @kalvdans: you're the debian guy. It seems buster doesn't have postgres 13 utilities in their packages;
> 
> https://packages.debian.org/search?keywords=postgres+client&searchon=names&suite=buster&section=all
> 
> We're using the 13 server, and postgres docs state "pg_dump cannot dump from PostgreSQL servers newer than its own major version; it will refuse to even try" (https://www.postgresql.org/docs/current/app-pgdump.html)
```
chn@rosa:~$ dpkg --search /usr/bin/pg_dump
postgresql-client-common: /usr/bin/pg_dump
```

2021-04-02 11:54 UTC, aapeliv commented
That's postgres 11 though?

2021-04-02 18:15 UTC, kalvdans commented
> That's postgres 11 though?

I'm using Debian Bullseye which have postgres 13. I don't know how forwards compatible pg_dump is, it doesn't say on the manual page.

2021-04-04 19:57 UTC, kalvdans commented
> I don't know how forwards compatible pg_dump is, it doesn't say on the manual page.

It's not.
```
pg_dump: server version: 13.0 (Debian 13.0-4); pg_dump version: 11.11 (Debian 11.11-0+deb10u1)
pg_dump: aborting because of server version mismatch
```

2021-04-04 20:00 UTC, aapeliv commented
It doesn't look like there's a stock python docker container with bullseye :(

2021-04-04 20:13 UTC, kalvdans commented
Do you think it could work by running `docker run postgis/postgis:13-3.0 pg_dump` instead of `pg_dump`?

2021-04-04 20:15 UTC, aapeliv commented
Yeah, we could definitely run it just as either a shell script, or a CI script (basically a shell script) and invoke pg_dump/docker

2021-04-04 20:19 UTC, kalvdans commented
> Yeah, we could definitely run it just as either a shell script, or a CI script (basically a shell script) and invoke pg_dump/docker

What do you mean? I thought about having the pg_dump command as a config variable, and define it as `docker run postgis/postgis:13-3.0 pg_dump` in the CI and just `pg_dump` when testing locally.

2021-04-04 20:25 UTC, aapeliv commented
I mean we can run it in CI as commands like in the tests (https://github.com/Couchers-org/couchers/blob/81781a7bb9314bec841188474fda06fe574082be/.gitlab-ci.yml#L173-L208)

But I think it's better to do as you're suggesting, just make the pg_dump cmd a variable

2021-04-04 21:10 UTC, kalvdans commented
It didn't work... The command `docker` was not found inside the container running the unit tests. Of course.

2021-04-11 15:21 UTC, aapeliv commented
Tried to just install `pg_dump` v13 from the postgres package repos in the test script, let's see if that works:

https://github.com/Couchers-org/couchers/commit/c85281de3fca47ff2135dd1bb86ebdb6d1379e6b

2021-04-14 19:58 UTC, kalvdans commented
@aapeli now only a single failure left, which I don't know how to solve:
```diff
--- migrations
+++ model
@@ -1252,6 +1252,13 @@
 --
 
 CREATE INDEX idx_page_versions_geom ON public.page_versions USING gist (geom);
+
+
+--
+-- Name: idx_users_geom; Type: INDEX; Schema: public; Owner: postgres
+--
+
+CREATE INDEX idx_users_geom ON public.users USING gist (geom);
 
 
 --
 ```

2021-04-14 20:38 UTC, kalvdans commented
TODO from the backend meeting: create new migrations instead of changing existing ones.

2021-04-25 13:16 UTC, kalvdans commented
All tests passes, ready for a new review @aapeliv! Will create another PR for the slugify escape bug

2021-04-25 17:11 UTC, aapeliv requested changes
Thanks, this is looking great!

Could you just add comments to `sort_pg_dump_output` and `test_migrations`. It's hard to decipher what's going on due to the regexpes and lambda functions :)... I guess you're basically sorting each section (delimited by `--`?) of the produced dump?

2021-04-25 17:11 UTC, aapeliv commented on app/backend/src/tests/test_db.py
> +def sort_pg_dump_output(output):
Could you add a docstring for this function?

2021-04-25 17:11 UTC, aapeliv commented on app/backend/src/tests/test_db.py
> +def test_migrations():
Could you add a comment/docstring as to what this test is doing?

2021-04-25 18:19 UTC, aapeliv approved these changes
LGTM!

2021-04-25 18:22 UTC, merged