Add dev/preview banner
Couchers-org/couchers pull request #995
Opened 2021-04-07 14:31 UTC by aapeliv

Also enabled grpc web debugging in previews

<img width="444" alt="Screen Shot 2021-04-07 at 10 29 49 am" src="https://user-images.githubusercontent.com/2975660/113883601-4c860800-978c-11eb-892d-a6ef7eb3bc20.png">
<img width="816" alt="Screen Shot 2021-04-07 at 10 29 40 am" src="https://user-images.githubusercontent.com/2975660/113883603-4d1e9e80-978c-11eb-821e-fa2d5e8235fc.png">

2021-04-07 15:59 UTC, aapeliv commented
Span hiding could be simplified with `useMediaQuery`

2021-04-07 17:33 UTC, aapeliv commented
<img width="678" alt="Screen Shot 2021-04-07 at 1 33 39 pm" src="https://user-images.githubusercontent.com/2975660/113909636-e4dcb680-97a5-11eb-93cd-f1e1b7184674.png">

2021-04-07 21:25 UTC, darrenvong requested changes
This floating thing looks kinda ugly :p It might look a bit better to have it above the nav bar instead (similar to how the alpha site did it)?

2021-04-07 21:25 UTC, darrenvong commented on app/frontend/src/components/EnvironmentBanner.tsx
> +    return <></>;
```suggestion
    return null;
```
React convention is to return null when you don't want to anything

2021-04-07 21:27 UTC, aapeliv commented
> This floating thing looks kinda ugly :p It might look a bit better to have it above the nav bar instead (similar to how the alpha site did it)?

It's just that it then offsets other stuff and e.g. the logged out landing index page starts scrolling, etc?

2021-04-07 21:41 UTC, darrenvong commented
> It's just that it then offsets other stuff and e.g. the logged out landing index page starts scrolling, etc?

True and it's probably gonna give false CSS positives in dev. How about having it on the bottom left next to where the React Query dev tools usually are?

2021-04-07 21:42 UTC, aapeliv commented
Just needs to be prominent enough that people don't get confused (in particular if they end up there by accident)... We already had someone ask me to move their profile from the preview db to prod.

2021-04-07 21:58 UTC, lucaslcode commented
Can we not merge this until #1003 is solved, there's a few work arounds I want to try

2021-04-07 22:00 UTC, aapeliv commented
> Can we not merge this until #1003 is solved, there's a few work arounds I want to try

Sure

2021-04-17 17:53 UTC, lucaslcode commented
Made it removeable, moved to bottom right, and made it pulse since I was worried about it not being seen down there

![image](https://user-images.githubusercontent.com/32044095/115122109-19bee980-9fae-11eb-94f1-3c89a86e5bbf.png)

2021-04-17 17:55 UTC, aapeliv commented
Does this now obstruct buttons that might appear on the bottom on a phone?

I had `pointerEvents: "none"` and a bit of transparency before so you could click through it, but obviously you can't do that if you can click it away. Or do you just click it away if you want to press a button there?

2021-04-17 20:12 UTC, darrenvong commented
> Or do you just click it away if you want to press a button there?

I think that's ok since it will only be on dev builds?

2021-04-17 20:16 UTC, darrenvong approved these changes

2021-04-17 21:17 UTC, merged